package gspot.com.sportify.utils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import gspot.com.sportify.Model.SportType;

/**
 * Created by amir on 5/22/16.
 */
public class DataBaseSports {

    public static void addToDataBase() {

        String[] s = new String[]{"Gliding",
                "Hang gliding",
                "Powered hang glider",
                "Human powered aircraft",
                "Model aircraft",
                "Parachuting",
                "Banzai skydiving",
                "BASE jumping",
                "Skydiving",
                "Skysurfing",
                "Wingsuit flying",
                "Paragliding",
                "Powered paragliding",
                "Paramotoring",
                "Ultralight aviation",
                "Aerobatics",
                "Air racing",
                "Field archery",
                "Flight archery",
                "Gungdo",
                "Indoor archery",
                "Kyūdō",
                "Popinjay",
                "Target archery",
                "Badminton",
                "Ball badminton",
                "Biribol",
                "Bossaball",
                "Fistball",
                "Footbag net",
                "Hooverball",
                "Peteca",
                "Pickleball",
                "Platform tennis",
                "Sepak takraw",
                "Sipa",
                "Tennis",
                "Throwball",
                "Volleyball",
                "Basketball",
                "Streetball",
                "Water basketball",
                "Wheelchair basketball",
                "Baseball",
                "Cricket",
                "Skateboarding",
                "Skysurfing",
                "Streetluge",
                "Snowboarding",
                "Wakesurfing",
                "Bodyboarding",
                "Riverboarding",
                "Skimboarding",
                "Windsurfing",
                "Wakeboarding",
                "Dodgeball",
                "Rock climbing",
                "Hiking",
                "Artistic cycling",
                "BMX",
                "Cyclo-cross",
                "Cross-country mountain biking",
                "Cycle polo",
                "Cycle speedway",
                "Downhill mountain biking",
                "Dirt jumping",
                "Freestyle BMX",
                "Hardcourt Bike Polo",
                "Road bicycle racing",
                "Track cycling",
                "Underwater cycling",
                "Unicycling",
                "Mountain unicycling",
                "Unicycle trials",
                "Unicycle hockey",
                "Unicycle basketball",
                "Aikido",
                "Judo",
                "Brazilian Jiu-Jitsu",
                "Sambo ",
                "Wrestling",
                "Sumo",
                "Choi Kwang-Do",
                "Cockfighting",
                "Boxing",
                "Bokator",
                "Capoeira",
                "Fujian White Crane",
                "Karate",
                "Kenpō",
                "Kickboxing",
                "Lethwei",
                "Muay Thai",
                "Pradal serey",
                "San shou",
                "Savate",
                "Shaolin kung fu",
                "Sikaran",
                "Silat",
                "Subak",
                "Taekkyeon",
                "Taekwondo",
                "Taido",
                "Tang Soo Do",
                "Wing Chun",
                "Zui quan",
                "Hapkido",
                "Jeet Kune Do",
                "Krav Maga",
                "Ninjutsu",
                "Wing Chun",
                "Kung fu",
                "Pocket billiards",
                "Fishing",
                "Fly fishing",
                "Rugby",
                "Football",
                "Soccer",
                "Rope jumping",
                "Water polo",
                "Hunting",
                "Racquetball",
                "Running",
                "Hockey",
                "Skiing ",
                "walking",
                "Backpacking",
                "Kayaking",
                "White water rafting",
                "Water polo",
                "Weightlifting",
                "Scuba Diving"};
        Arrays.sort(s);
    /*Convert the array to a list*/
        List<String> sports = new ArrayList<>();

        /*populate the list*/
        for (String item : s)
            sports.add(item.toUpperCase());

        for (String item : sports)
            SportType.createASportType(item, null);
    }
}
